update ci setup

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,7 +12,7 @@ jobs:
 
     steps:
       - checkout
-      
+
       - restore_cache:
           keys:
           - v1-dependencies-{{ checksum "requirements.txt" }}
@@ -20,8 +20,12 @@ jobs:
       - run:
           name: install dependencies
           command: |
-            apt-get update 
-            aapt-get update && apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev libpng-dev build-essential
+            sudo rm /etc/apt/sources.list
+            echo "deb http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
+            echo "deb-src http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
+            echo "Acquire::Check-Valid-Until false;" | sudo tee -a /etc/apt/apt.conf.d/10-nocheckvalid
+            echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | sudo tee -a /etc/apt/preferences.d/10-archive-pin
+            apt-get update && apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev libpng-dev build-essential
             apt-get install imagemagick ghostscript -y
             apt-get install libmagickwand-dev -y
             apt-get install zlib1g-dev -y
@@ -30,32 +34,32 @@ jobs:
             apt-get install ImageMagick -y
             apt-get install libpython-dev -y
             apt-get install python-pip -y
-            
-            pip install virtualenv 
+
+            pip install virtualenv
             virtualenv venv
             . venv/bin/activate
             pip install -r requirements.txt
             pip install codecov pytest pytest-cov
-              
+
       - save_cache:
           paths:
             - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
-        
+
       - run:
           name: run tests
           command: |
             . venv/bin/activate
-            pytest -vs 
-            
+            pytest -vs
+
       -  run:
           name: upload coverage report
           command: |
             . venv/bin/activate
             pytest --cov=./
-            codecov || echo "Error in uploading coverage reports to codecov.io."      
+            codecov || echo "Error in uploading coverage reports to codecov.io."
 
       - store_artifacts:
           path: test-reports
           destination: test-reports
-          
+
